name = Red v5 Test
scale = 1
filename = Reko_052.fbx
marketplaceID = {8c8ca0ab-4f23-470d-b8c6-ba9593f09ef4}
texdir = textures
joint = jointLean = Spine
joint = jointEyeRight = RightEye
joint = jointRoot = Hips
joint = jointLeftHand = LeftHand
joint = jointRightHand = RightHand
joint = jointHead = Head
joint = jointNeck = Neck
joint = jointEyeLeft = LeftEye
freeJoint = RightForeArm
freeJoint = RightArm
freeJoint = LeftForeArm
freeJoint = LeftArm
jointIndex = LeftHandIndex1 = 66
jointIndex = Body = 1
jointIndex = LeftHandPinky2 = 57
jointIndex = LeftForeArm = 54
jointIndex = Head = 82
jointIndex = LeftHand = 55
jointIndex = RightHandPinky1 = 42
jointIndex = RightHandMiddle4 = 50
jointIndex = LeftHandThumb2 = 72
jointIndex = RightShoulder = 23
jointIndex = LeftToe_End_end = 19
jointIndex = RightHandIndex4_end = 36
jointIndex = LeftLeg = 15
jointIndex = RightHandIndex3 = 34
jointIndex = LeftHandRing4_end = 65
jointIndex = LeftHandIndex4 = 69
jointIndex = HeadTop_End_end = 94
jointIndex = RightHandMiddle1 = 47
jointIndex = LeftHandThumb4 = 74
jointIndex = simTail2 = 5
jointIndex = Hips = 3
jointIndex = LeftHandMiddle4_end = 80
jointIndex = simLeftEar1 = 86
jointIndex = RightHandMiddle3 = 49
jointIndex = prim0.004 = 0
jointIndex = simTail3_end = 7
jointIndex = RightHandIndex1 = 32
jointIndex = simTail1 = 4
jointIndex = RightHandRing1 = 37
jointIndex = RightHandRing2 = 38
jointIndex = LeftArm = 53
jointIndex = LeftHandIndex3 = 68
jointIndex = Neck = 81
jointIndex = RightHandThumb3 = 29
jointIndex = LeftHandIndex2 = 67
jointIndex = HifiArmature = 2
jointIndex = simRightEar1 = 83
jointIndex = LeftHandIndex4_end = 70
jointIndex = LeftHandRing4 = 64
jointIndex = RightHandRing3 = 39
jointIndex = RightToe_End_end = 13
jointIndex = simRightEar2_end = 85
jointIndex = RightHandPinky4 = 45
jointIndex = HeadTop_End = 93
jointIndex = LeftFoot = 16
jointIndex = simRightEar2 = 84
jointIndex = RightEye = 91
jointIndex = RightHandThumb4 = 30
jointIndex = RightArm = 24
jointIndex = LeftHandPinky4 = 59
jointIndex = RightUpLeg = 8
jointIndex = LeftEye_end = 90
jointIndex = Spine = 20
jointIndex = RightToe_End = 12
jointIndex = LeftHandPinky3 = 58
jointIndex = RightHandThumb2 = 28
jointIndex = Spine2 = 22
jointIndex = LeftHandThumb1 = 71
jointIndex = RightHandPinky4_end = 46
jointIndex = RightHandPinky3 = 44
jointIndex = prim0.005 = 95
jointIndex = LeftHandMiddle4 = 79
jointIndex = Spine1 = 21
jointIndex = LeftHandThumb3 = 73
jointIndex = LeftHandRing1 = 61
jointIndex = LeftToeBase = 17
jointIndex = RightHandRing4 = 40
jointIndex = RightHandMiddle2 = 48
jointIndex = RightHandMiddle4_end = 51
jointIndex = RightForeArm = 25
jointIndex = LeftHandThumb4_end = 75
jointIndex = simTail3 = 6
jointIndex = LeftHandMiddle3 = 78
jointIndex = LeftEye = 89
jointIndex = RightHandThumb1 = 27
jointIndex = LeftHandPinky1 = 56
jointIndex = RightHandThumb4_end = 31
jointIndex = LeftHandRing3 = 63
jointIndex = LeftHandMiddle2 = 77
jointIndex = RightHand = 26
jointIndex = LeftUpLeg = 14
jointIndex = LeftHandPinky4_end = 60
jointIndex = LeftHandMiddle1 = 76
jointIndex = LeftToe_End = 18
jointIndex = RightToeBase = 11
jointIndex = LeftHandRing2 = 62
jointIndex = RightLeg = 9
jointIndex = RightHandRing4_end = 41
jointIndex = RightHandPinky2 = 43
jointIndex = simLeftEar2 = 87
jointIndex = LeftShoulder = 52
jointIndex = RightEye_end = 92
jointIndex = RightHandIndex4 = 35
jointIndex = RightHandIndex2 = 33
jointIndex = simLeftEar2_end = 88
jointIndex = RightFoot = 10
